import SwiperCardStack from "./SwiperCardStack";
import _core1 from "../../assets/core1.png";
import _core2 from "../../assets/core2.png";
import _core3 from "../../assets/core3.png";
import './index.less'

export default () => {
  return (
    <div className="homePage5">
      <div className="pageTitle">Bitmodel core value</div>
      <div className="pageSubTitle">
        Bitmodel, Cherishing Every Contribution to AI
      </div>
      <div className="coreWrap">
        <div className="core1Wrap">
          <img src={_core1} alt="" className="core1Img" />
          <div className="core1">
            <div className="bg"></div>
            <div className="titleWrap">
              <div className="sort">
                01
              </div>
              <div className="title">Bitcoin Virtual Machine（BVM）</div>
            </div>

            <p className="content">
              As the foundation of Bitmodel, BVM provides a safe and decentralized environment to run scripts following the Bitcoin protocol. Compared with the Ethereum Virtual Machine (EVM), BVM enjoys stronger scalability, making it an ideal platform to deal with high-volume transactions and complex computing required by AI. In addition, built with OP_CODES, BVM naturally supports Turing-complete smart contracts. It is also noteworthy that, thanks to the discrete state in UTXO, the smart contracts implemented on BVM are more independent to each other than those implemented on EVM, and hence lead to higher performance with parallel computing.
            </p>

          </div>


        </div>
        <div className="coreBottom">
          <div className="coreLeft">
            <div className="core2Wrap">


              <div className="core2">
                <div className="bg"></div>
                <div className="titleWrap">
                  <div className="sort">
                    02
                  </div>
                  <div className="title">Contribution Flows</div>
                </div>
                <p className="content">
                  Bitmodel aims to organize AI algorithms into a direcional graph, recording the reliance between various sources. Thus, Bitmodel is able to trace how a technique contributes to an AI service, making sure not only the customer-side models (e.g., ChatGPT and Stable Diffusion) but more importantly the underlying techniques (e.g., Transformer and Diffusion models) could be adequately rewarded. Such an incentive mechanism is expected to inspire all levels of studies in AI, stimulate continuous development of high-quality models, and encourage community cooperation.
                </p>
              </div>
              <img src={_core2} alt="" className="core2Img" />
            </div>
            <div className="core456">
              <div className="core4">
                <div className="bg"></div>
                <div className="titleWrap">
                  <div className="sort">
                    04
                  </div>
                  <div className="title">Initial Model Offering</div>
                </div>
                <p className="content">
                Once developers have successfully trained models that address the proposed IMI tasks, they can release their models through the Bitmodel platform. This marks the beginning of the Initial Model Offering (IMO). In the IMO stage, developers may offer specific tokens associated with their models, provided that the models meet certain criteria established by the community. High-quality models released through the IMO process are eligible for the implementation of model-specific tokenomics. This enables developers to establish a self-sustaining economic system around their models, allowing them to capture a portion of the value generated by their creation. 
                </p>
              </div>
              <div className="core56">
                <div className="core5">
                  <div className="bg"></div>
                  <div className="titleWrap">
                    <div className="sort">
                      05
                    </div>
                    <div className="title">Customized Agent Framework</div>
                  </div>
                  <p className="content">
                  Committed to support worldwide AI applications, our platform adopts a unified and standardized framework for Agent development, in which way we manage to build up a highly efficient AI ecosystem, maximize the practical value of AI models, and simplify the development of AI services.
                  </p>
                </div>
                <div className="core6">
                  <div className="bg"></div>
                  <div className="titleWrap">
                    <div className="sort">
                      06
                    </div>
                    <div className="title">Decentralized AI Infrastructure</div>
                  </div>
                  <p className="content">
                  To address the issue of limited computation resources, our platform adopts a decentralized computing strategy, which is able to distribute model serving to scattered resources and hence improve the accessibility of large-scale AI models. Such a design encourages the contribution to and the application of AI. The same strategy is also applicable to alleviating the problem of data scarcity.
                  </p>
                </div>
              </div>
            </div>

          </div>
          <div className="coreRight">
            <div className="core3Wrap">
              <div className="core3">
                <div className="bg"></div>
                <div className="titleWrap">
                  <div className="sort">
                    03
                  </div>
                  <div className="title">Initial Model Investing</div>
                </div>
                <p className="content">
                  Initial Model Investing (IMI) addresses the fundamental challenge of resource scarcity in model development. Many developers lack the necessary computational power and high-quality data required to train large models, often due to the prohibitive costs involved. Bitmodel provides a solution through IMI, enabling users to invest tokens on specific algorithmic tasks that address their needs. These tasks serve as prompts for developers, who can then leverage their expertise to develop models that solve the identified problems. In this way, users signal their interest in particular functionalities and incentivize developers to focus their efforts on addressing those needs.
                </p>
              </div>
              <img src={_core3} alt="" className="core3Img" />

            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
